services:
  prefect-server:
    image: prefecthq/prefect:2-latest
    restart: always
    volumes:
      - .:/app
      - prefect-data:/root/.prefect
    working_dir: /app
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0"]
    environment:
      - PYTHONPATH=/app
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    ports:
      - "4200:4200"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  prefect-data:
  postgres-data: